{
 "title": "host metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "network_interface",
    "query": {
     "query": "label_values(node_network_up,device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{}[1m])",
     "legendFormat": "{{cpu}} - {{mode}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Network Up",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_up{device=~\"${network_interface}\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Receive Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"${network_interface}\"}[1m]) / on(device) node_network_speed_bytes{device=~\"${network_interface}\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmit Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"${network_interface}\"}[1m]) / on(device) node_network_speed_bytes{device=~\"${network_interface}\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Receive Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{device=~\"${network_interface}\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmit Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_drop_total{device=~\"${network_interface}\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"${network_interface}\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"${network_interface}\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "FD Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_filefd_allocated / on(instance) node_filefd_maximum",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}