controller:
  replicaCount: 3

  ingressClassResource:
    name: nginx
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx"

  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: https

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

defaultBackend:
  enabled: true
  replicaCount: 3
