{
 "title": "Spring Webflux",
 "tags": [
  "micrometer",
  "prometheus",
  "spring",
  "webflux"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instances",
    "label": "Instances",
    "query": {
     "query": "label_values(application_ready_time_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "http request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{instance=~\"$instances\"}[1m])",
     "legendFormat": "{{method}} & {{instance}} & {{uri}} - {{status}} & {{outcome}}"
    }
   ]
  },
  {
   "title": "system cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\"$instances\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "process cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\"$instances\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instances\", area=\"heap\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reactor Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "sched_bounded_elastic_scheduler_tasks_active_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(sched_bounded_elastic_scheduler_tasks_active_seconds_count{instance=~\"$instances\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "sched_bounded_elastic_scheduler_tasks_pending_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(sched_bounded_elastic_scheduler_tasks_pending_seconds_count{instance=~\"$instances\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "sched_parallel_scheduler_tasks_active_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(sched_parallel_scheduler_tasks_active_seconds_count{instance=~\"$instances\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "sched_parallel_scheduler_tasks_pending_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(sched_parallel_scheduler_tasks_pending_seconds_count{instance=~\"$instances\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}