{
 "title": "app metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "http",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "http request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{uri=\"/ping\"}[1m])",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "http request latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{uri=\"/ping\"}[1m])\n/\nrate(http_server_requests_seconds_count{uri=\"/ping\"}[1m])",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "netty",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "netty_eventexecutor_workers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "netty_eventexecutor_workers", "legendFormat": "{{status}}" }
     ]
    },
    {
     "title": "netty_eventexecutor_tasks_pending",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "netty_eventexecutor_tasks_pending",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "netty_allocator_memory_used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
     "targets": [
      { "expr": "netty_allocator_memory_used", "legendFormat": "{{status}}" }
     ]
    }
   ]
  },
  {
   "title": "logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "logback_events_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
     "targets": [
      { "expr": "logback_events_total", "legendFormat": "{{status}}" }
     ]
    }
   ]
  },
  {
   "title": "executor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "executor_active_threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
     "targets": [
      { "expr": "executor_active_threads", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "executor_completed_tasks_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
     "targets": [
      { "expr": "executor_completed_tasks_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "executor_pool_core_threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 316 },
     "targets": [
      { "expr": "executor_pool_core_threads", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "executor_pool_max_threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 316 },
     "targets": [
      { "expr": "executor_pool_max_threads", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "executor_pool_core_threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 324 },
     "targets": [
      { "expr": "executor_pool_core_threads", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "executor_queue_remaining_tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 324 },
     "targets": [
      { "expr": "executor_queue_remaining_tasks", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "executor_queued_tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 332 },
     "targets": [
      { "expr": "executor_queued_tasks", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "system_cpu_count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "system_cpu_count", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "load average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "system_load_average_1m", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "cpu usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "system_cpu_usage", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "process_files_open_files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
     "targets": [
      { "expr": "process_files_open_files", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "process fd utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "process_files_open_files / process_files_max_files",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "process_cpu_usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "process_cpu_usage", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "process_cpu_time_ns_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(process_cpu_time_ns_total{}[1m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "disk_free_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "disk_free_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "disk_total_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "disk_total_bytes", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "jvm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "jvm info",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_info",
       "legendFormat": "{{runtime}} - {{vendor}} - {{version}}"
      }
     ]
    },
    {
     "title": "jvm max memory",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "jvm_memory_max_bytes{}", "legendFormat": "{{area}} - {{id}}" }
     ]
    },
    {
     "title": "jvm used memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "jvm_memory_used_bytes", "legendFormat": "{{area}} - {{id}}" }
     ]
    },
    {
     "title": "jvm_threads_live_threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jvm_threads_states_threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "targets": [
      { "expr": "jvm_threads_states_threads", "legendFormat": "{{state}}" }
     ]
    }
   ]
  }
 ]
}