{
 "title": "container metrics",
 "tags": [
  "cadvisor",
  "container-metrics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "container_name",
    "query": {
     "query": "label_values(container_start_time_seconds,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "no. cpu cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "machine_cpu_cores", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "no. cpu physical cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "machine_cpu_physical_cores", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "memory capacity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "machine_memory_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "swap capacity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "machine_swap_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "container uptime",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_start_time_seconds{id!=\"/\", name=~\"${container_name}\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "cpu utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
       "legendFormat": "{{name}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "cpu load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_cpu_load_average_10s{id!=\"/\", name=~\"${container_name}\"}[1m]",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "cpu tasks state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_tasks_state{id!=\"/\", name=~\"${container_name}\"}",
       "legendFormat": "{{name}} - {{state}}"
      }
     ]
    },
    {
     "title": "memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(container_memory_usage_bytes{id!=\"/\", name=~\"${container_name}\"}[1m])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "no. file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "container_file_descriptors{id!=\"/\", name=~\"${container_name}\"}[1m]",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "no. ulimit soft",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "container_ulimits_soft{id!=\"/\", name=~\"${container_name}\"}",
       "legendFormat": "{{name}} - {{ulimit}}"
      }
     ]
    },
    {
     "title": "no. processes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "container_processes{id!=\"/\", name=~\"${container_name}\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "no. sockets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "container_sockets{id!=\"/\", name=~\"${container_name}\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "no. threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "container_threads{id!=\"/\", name=~\"${container_name}\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "thread utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "container_threads{id!=\"/\", name=~\"${container_name}\"} / on (name) container_threads_max",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "network receive rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
       "legendFormat": "{{name}} - {{interface}}"
      }
     ]
    },
    {
     "title": "network transmit rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
       "legendFormat": "{{name}} - {{interface}}"
      }
     ]
    },
    {
     "title": "network receive error rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "e/s" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_errors_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
       "legendFormat": "{{name}} - {{interface}}"
      }
     ]
    },
    {
     "title": "network transmit error rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "e/s" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_errors_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
       "legendFormat": "{{name}} - {{interface}}"
      }
     ]
    },
    {
     "title": "network receive packet dropped rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_packets_dropped_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
       "legendFormat": "{{name}} - {{interface}}"
      }
     ]
    },
    {
     "title": "network transmit packet dropped rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_packets_dropped_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
       "legendFormat": "{{name}} - {{interface}}"
      }
     ]
    },
    {
     "title": "tcp usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "container_network_tcp_usage_total{id!=\"/\", name=~\"$container_name\"}",
       "legendFormat": "{{name}} - {{tcp_state}}"
      }
     ]
    },
    {
     "title": "udp usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "targets": [
      {
       "expr": "container_network_udp_usage_total{id!=\"/\", name=~\"$container_name\"}",
       "legendFormat": "{{name}} - {{udp_state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "disk i/o",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "fs reads rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
       "legendFormat": "{{name}} - {{device}}"
      }
     ]
    },
    {
     "title": "fs writes rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(container_fs_writes_bytes_total{id!=\"/\", name=~\"${container_name}\"}[1m])",
       "legendFormat": "{{name}} - {{device}}"
      }
     ]
    },
    {
     "title": "fs reads latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "container_fs_read_seconds_total{}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "fs write latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "container_fs_write_seconds_total{}",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  }
 ]
}